// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm5rudpuRrdF1WWVjCv9EHb_nzpd0hA3s',
    appId: '1:376461501752:web:769b756832c909ba1a4dcd',
    messagingSenderId: '376461501752',
    projectId: 'oaap-1833b',
    authDomain: 'oaap-1833b.firebaseapp.com',
    storageBucket: 'oaap-1833b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuWDoxRXAdIFS1orWaFZTGsbfgVppVQyM',
    appId: '1:376461501752:android:c6a57b3a73850f271a4dcd',
    messagingSenderId: '376461501752',
    projectId: 'oaap-1833b',
    storageBucket: 'oaap-1833b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH6A7iflMzQZqLOvpDAG-S7qZ7K1TmN-E',
    appId: '1:376461501752:ios:7e4273ff26bd7e971a4dcd',
    messagingSenderId: '376461501752',
    projectId: 'oaap-1833b',
    storageBucket: 'oaap-1833b.appspot.com',
    iosClientId: '376461501752-r0q3i0g0ms1hii4o96ht31gtoj8nl5n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.oaap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH6A7iflMzQZqLOvpDAG-S7qZ7K1TmN-E',
    appId: '1:376461501752:ios:7e4273ff26bd7e971a4dcd',
    messagingSenderId: '376461501752',
    projectId: 'oaap-1833b',
    storageBucket: 'oaap-1833b.appspot.com',
    iosClientId: '376461501752-r0q3i0g0ms1hii4o96ht31gtoj8nl5n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.oaap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm5rudpuRrdF1WWVjCv9EHb_nzpd0hA3s',
    appId: '1:376461501752:web:bc61f64bcab14d661a4dcd',
    messagingSenderId: '376461501752',
    projectId: 'oaap-1833b',
    authDomain: 'oaap-1833b.firebaseapp.com',
    storageBucket: 'oaap-1833b.appspot.com',
  );
}
